version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mysql:5.6

      - add_ssh_keys:
          fingerprints:
            - "54:1c:6c:63:fb:78:34:85:0e:51:59:aa:98:b4:15:6a"

      - deploy:
          name: Capistrano deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi
            bundle exec cap production deploy