version: 2
jobs:
  build:
    - add_ssh_keys:
      fingerprints:
        - "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"

    - deploy:
      name: Capistrano deploy
      command:
        bundle exec cap production deploy