default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# ローカル環境（rails sで起動）
development:
  <<: *default
  database: mynote_development
  username: root
  password:
  socket: /tmp/mysql.sock
# docker環境(docker-compose upで起動) config/puma.rbも変更すること
# development:
#   <<: *default
#   database: mynote_development
#   username: root
#   password: password
#   host: db
#
# test:
#   <<: *default
# database: app_test

# EC2からRDSに接続
production:
  <<: *default
  adapter: mysql2
  charset: utf8
  database: <%= Rails.application.credentials.aws[:rds][:DATABASE_NAME] %>
  username: <%= Rails.application.credentials.aws[:rds][:DATABASE_USERNAME] %>
  password: <%= Rails.application.credentials.aws[:rds][:DATABASE_PASSWORD] %>
  host: <%= Rails.application.credentials.aws[:rds][:DATABASE_HOST] %>
# EC2内のMySQLに接続
# production:
#   <<: *default
#   database: my_app_production
#   username: root
#   password: password
#   socket: /var/lib/mysql/mysql.sock

# ECSからRDSに接続
# production:
#   <<: *default
#   database: <%= ENV['DB_DATABASE'] %>
#   adapter: mysql2
#   encoding: utf8mb4
#   charset: utf8mb4
#   collation: utf8mb4_general_ci
#   host: <%= ENV['DB_HOST'] %>
#   username: <%= ENV['DB_USERNAME'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
