default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  # database: my_app_development
  username: root
  password: password
  database: mynote_development     
  host: db

# test:
#   <<: *default
#   database: my_app_test

production:
  <<: *default
  database: my_app_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock