default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  #my_appはローカルのDB
  database: my_app_development
  encoding: utf8

  #以下はdockerのDB
  # database: mynote_development     
  # username: root
  # password: password
  # host: db

test:
  <<: *default
  database: my_app_test

# production:
#   <<: *default
#   # RDSに接続
#   database: mynote_production
#   username: <%= Rails.application.credentials.rds[:DATABASE_USERNAME] %>
#   password: <%= Rails.application.credentials.rds[:DATABASE_PASSWORD] %>
#   host: <%= Rails.application.credentials.rds[:DATABASE_HOST] %>
#   encoding: utf8

production:
  # EC2内のMySQLに接続
  <<: *default
  database: my_app_production
  username: root
  password: password
  encoding: utf8