default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

# my_appはローカルのDB
development:
  <<: *default
  database: mynote_development
  socket: /tmp/mysql.sock
# docker-compose環境
# development:
#   <<: *default
#   database: mynote_development
#   username: root
#   password: password
#   host: db
#
# test:
#   <<: *default
# database: app_test

# ECSからRDSに接続
# production:
#   <<: *default
#   database: <%= ENV['DB_DATABASE'] %>
#   adapter: mysql2
#   encoding: utf8mb4
#   charset: utf8mb4
#   collation: utf8mb4_general_ci
#   host: <%= ENV['DB_HOST'] %>
#   username: <%= ENV['DB_USERNAME'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
#
# EC2からRDSに接続
# production:
#   <<: *default
#   adapter: mysql2
#   charset: utf8
#   database: mynote_production
#   username: <%= Rails.application.credentials.rds[:DATABASE_USERNAME] %>
#   password: <%= Rails.application.credentials.rds[:DATABASE_PASSWORD] %>
#   host: <%= Rails.application.credentials.rds[:DATABASE_HOST] %>
#   encoding: utf8

# EC2内のMySQLに接続
# production:
#   <<: *default
#   database: my_app_production
#   username: root
#   password: password
#   socket: /var/lib/mysql/mysql.sock
#   encoding: utf8
